[package]
name = "hello-rocket-adv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
rocket_contrib = "0.4.7"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }